# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flixer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flixer
  # This pulls in the latest version of Alamofire >= 4.4 but less than 5.0.
  #pod 'Alamofire', '~> 4.4'
  
  pod "AlamofireImage"
  
  # Add additional dependencies
  #pod 'OAuthSwift', '~> 1.1.0'
  #pod 'OAuthSwiftAlamofire'

  target 'flixerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flixerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
